// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl_qo0DSo2teQf6Mc3mGuFEZceogV80do',
    appId: '1:187682904446:web:bc4e56e6148c54532a7b2f',
    messagingSenderId: '187682904446',
    projectId: 'mynoteproject-d4db0',
    authDomain: 'mynoteproject-d4db0.firebaseapp.com',
    storageBucket: 'mynoteproject-d4db0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9RPxowvO0yAaimguPDvSs8VKiC6AAaAI',
    appId: '1:187682904446:android:f1bfb254c8a597062a7b2f',
    messagingSenderId: '187682904446',
    projectId: 'mynoteproject-d4db0',
    storageBucket: 'mynoteproject-d4db0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRLaP2yZQBZQaus-kkPlmCCFN2rQoB83s',
    appId: '1:187682904446:ios:0405ad5c37e5be422a7b2f',
    messagingSenderId: '187682904446',
    projectId: 'mynoteproject-d4db0',
    storageBucket: 'mynoteproject-d4db0.appspot.com',
    iosBundleId: 'com.example.mynotePro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRLaP2yZQBZQaus-kkPlmCCFN2rQoB83s',
    appId: '1:187682904446:ios:0405ad5c37e5be422a7b2f',
    messagingSenderId: '187682904446',
    projectId: 'mynoteproject-d4db0',
    storageBucket: 'mynoteproject-d4db0.appspot.com',
    iosBundleId: 'com.example.mynotePro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl_qo0DSo2teQf6Mc3mGuFEZceogV80do',
    appId: '1:187682904446:web:a0942af6c38549de2a7b2f',
    messagingSenderId: '187682904446',
    projectId: 'mynoteproject-d4db0',
    authDomain: 'mynoteproject-d4db0.firebaseapp.com',
    storageBucket: 'mynoteproject-d4db0.appspot.com',
  );
}
